### ISSUE TITLE
homebrew installation fails

### ISSUE THREAD

**Issue by nicks** [technicallyjosh/easy-params#3]
fyi - homebrew installation currently fails for me with this error

```
Error: easy-params: wrong number of arguments (given 1, expected 0)
```

i think it's because `:bottle unneeded` is an error in modern versions of homebrew
https://github.com/Homebrew/brew/pull/11239

but the easy-params formula still has it
https://github.com/technicallyjosh/homebrew-easy-params/blob/master/easy-params.rb#L9

manually editing the local formula to remove that line fixes it

**Comment by dotjoshrc** [comment]
Holy crap, sorry I missed this one. Lemme whip together a fix. Thanks for letting me know!

**Comment by dotjoshrc** [comment]
This is now fixed. Although just simply tapping doesn't work to update it. I had to do a `brew untap technicallyjosh/easy-params` and then just tap again or install directly with `brew install technicallyjosh/easy-params/easy-params`
